export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER = "GET_ALL_USER"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"